apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Admin@123
            - name: MYSQL_DATABASE_ORDER
              value: orderdb
            - name: MYSQL_USER_ORDER
              value: orderdb-user
            - name: MYSQL_PASSWORD_ORDER
              value: Admin@123
            - name: MYSQL_DATABASE_PAYMENT
              value: paymentdb
            - name: MYSQL_USER_PAYMENT
              value: paymentdb-user
            - name: MYSQL_PASSWORD_PAYMENT
              value: Admin@123
            - name: MYSQL_DATABASE_PRODUCT
              value: productdb
            - name: MYSQL_USER_PRODUCT
              value: productdb-user
            - name: MYSQL_PASSWORD_PRODUCT
              value: Admin@123
          ports:
            - containerPort: 3306
