apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapp
  template:
    metadata:
      labels:
        app: shoppingapp
    spec:
      containers:
        - name: shoppingapp-container
          image: suriya1776/startruck:shoppingapp_v1.2
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_PRODUCT_URL
              valueFrom:
                configMapKeyRef:
                  name: shoppingapp-config
                  key: REACT_APP_PRODUCT_URL
            - name: REACT_APP_PAYMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: shoppingapp-config
                  key: REACT_APP_PAYMENT_URL
            - name: REACT_APP_ORDER_URL
              valueFrom:
                configMapKeyRef:
                  name: shoppingapp-config
                  key: REACT_APP_ORDER_URL

